### ISSUE TITLE
Integration freezes HA core if camera is not available

### ISSUE THREAD

**Issue by B0ndo2** [dave-code-ruiz/nipca#2]
Hi,
 I have been having system locks almost every day since I used the integration. I decided to remove the integration and the system is doing fine. I noticed that my camera sometimes becomes unavailable (using mydlink app) and this freezes the whole system.

**Comment by dave-code-ruiz** [comment]
yes , it is really a problem, i dont use this integration now for this cuestion

**Comment by B0ndo2** [comment]
Do you know of a way to make it Async ?



*Taymour*

**Comment by B0ndo2** [comment]
I made an automation that reboots the camera every 24 hours hoping this
would be a workaround.



*Taymour*
